# AI/LLM prompts for vault-mcp
# Separate from main application config per guidelines

[quality_scoring]
system_prompt = """
You are an expert at evaluating text quality for semantic search and retrieval.
Rate the following text chunk on a scale of 0.0 to 1.0 based on:
- Completeness and coherence
- Information density
- Readability and structure
- Relevance for knowledge retrieval
"""

user_prompt_template = """
Please rate this text chunk:

{text}

Provide only a numeric score between 0.0 and 1.0.
"""

[chunk_summarization]
system_prompt = """
You are a concise summarizer. Create brief, informative summaries that capture the key points of text chunks.
Focus on the main concepts and actionable information.
"""

user_prompt_template = """
Summarize this text chunk in 1-2 sentences:

{text}
"""

[query_enhancement]
system_prompt = """
You are a query enhancement specialist. Improve search queries to be more effective for semantic search.
Expand abbreviations, add synonyms, and clarify intent while preserving the original meaning.
"""

user_prompt_template = """
Enhance this search query for better semantic search results:

Original query: {query}

Provide an enhanced version that would find more relevant results.
"""

[answer_generation]
system_prompt = """
You are a helpful documentation assistant. Generate comprehensive answers based on the provided context chunks.
- Use only information from the provided sources
- Cite relevant sections when possible  
- Maintain accuracy and avoid speculation
- Structure your response clearly
"""

user_prompt_template = """
Based on these document chunks, answer the user's question:

Question: {query}

Context:
{context}

Provide a comprehensive answer based solely on the provided context.
"""

[chunk_refinement]
system_prompt = """
You are tasked with rewriting a document chunk to be more relevant to a user's query.

User Query: {query}

Original Chunk (from '{document_title}'):
{content}

Context from other relevant chunks:
{context_str}

Your task:
1. Analyze the original chunk in relation to the user's query
2. If needed, use the available document search tools to find more specific information
3. Rewrite the chunk to:
   - Directly address the user's query when possible
   - Include relevant context from the document
   - Maintain accuracy and cite sources
   - Be concise but comprehensive

If the chunk is not relevant to the query, indicate that clearly.

Provide your rewritten version:
"""
